[build]
  command = "node build.js"
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/identity"
  to = "https://identity.netlify.com/v1/gotrue/api"
  status = 200
  force = true

[context.production]
  environment = { NODE_ENV = "production" }
